### ISSUE TITLE
proto-lens-setup fails to build with ghc-9.12 (Cabal-3.14)

### ISSUE THREAD

**Issue by juhp** [google/proto-lens#529]
For stackage nightly:

```
       Building library for proto-lens-setup-0.4.0.9...                                                         05:10:04 [64/566999]
       [1 of 2] Compiling Data.ProtoLens.Setup             
       /home/curators/work/unpack-dir/unpacked/proto-lens-setup-0.4.0.9-ddebf9c27d57655a1c5a4e0c4ee1947b8ce02d4edb074f1c9f7b282af0f1
d544/src/Data/ProtoLens/Setup.hs:173:33: error: [GHC-83865]                                                                         
           • Couldn't match type: Distribution.Utils.Path.SymbolicPathX  
                                    Distribution.Utils.Path.OnlyRelative                              
                                    Distribution.Utils.Path.Pkg                                                                     
                                    Distribution.Utils.Path.File
                            with: [Char]                                                                                            
             Expected: [FilePath]                                 
               Actual: [Distribution.Utils.Path.RelativePath                                                                        
                          Distribution.Utils.Path.Pkg Distribution.Utils.Path.File]
           • In the second argument of ‘mapM’, namely
               ‘(extraSrcFiles $ localPkgDescr l)’                                                                                               In the second argument of ‘(<$>)’, namely            
               ‘mapM (match $ localPkgDescr l) (extraSrcFiles $ localPkgDescr l)’
             In a stmt of a 'do' block:                                                                                             
               files <- concat
                          <$>                                                                                                       
                            mapM (match $ localPkgDescr l) (extraSrcFiles $ localPkgDescr l)                                        
           |                                                      
       173 |                                (extraSrcFiles $ localPkgDescr l)               
           |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
                                                                  
       /home/curators/work/unpack-dir/unpacked/proto-lens-setup-0.4.0.9-ddebf9c27d57655a1c5a4e0c4ee1947b8ce02d4edb074f1c9f7b282af0f1
d544/src/Data/ProtoLens/Setup.hs:182:16: error: [GHC-83865]                                                                         
           • Couldn't match type: Distribution.Utils.Path.SymbolicPathX
                                    allowAbs0 dir0 file0
                            with: [Char]
             Expected: IO [FilePath]
               Actual: IO
                         [Distribution.Utils.Path.SymbolicPathX allowAbs0 dir0 file0]
           • In the expression:
               matchDirFileGlob normal (specVersion desc) "." f
             In an equation for ‘match’:
                 match desc f = matchDirFileGlob normal (specVersion desc) "." f
           |
       182 | match desc f = matchDirFileGlob normal (specVersion desc) "." f
           |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:
```

**Comment by ysangkok** [comment]
Note that there is also some discussion on this issue here:

* https://github.com/google/proto-lens/issues/526#issuecomment-4152610016

**Comment by blackgnezdo** [comment]
OK, I reverted the cabal file revision for `proto-lens-setup`. So much for trying new things. Let me know if it helps?

**Comment by jchia** [comment]
It still does not work. Any updates? https://github.com/google/proto-lens/issues/526#issuecomment-4152610016

**Comment by blackgnezdo** [comment]
Pushed them all
