### ISSUE TITLE
Hackage release with GHC 9.12 support

### ISSUE THREAD

**Issue by carbolymer** [google/proto-lens#526]
There hasn't been a hackage release for a while. In the meantime GHC 9.12 support was merged to `master` together with version bumps for the dependencies.

**Comment by carbolymer** [comment]
@blackgnezdo Do you know if you could release to hackage soon?

**Comment by erikd** [comment]
Current `master` branch also builds with `ghc-9.14`.

**Comment by blackgnezdo** [comment]
I revised the cabal files on hackage to match the current state of the tree compatible with ghc up to 9.14.

**Comment by carbolymer** [comment]
@blackgnezdo Why did you do that instead of releasing full source tree? Now the hackage release is not building with GHC 9.12. Can you release a full package on hackage please?

```
Failed to build proto-lens-setup-0.4.0.9.
Build log (
/home/mgalazyn/.local/share/cabal/logs/ghc-9.12.2/proto-lens-setup-0.4.0.9-4f0663ecef73b8c0b089505a6ea252e57b0c05155fef1fa5082fcabc45e865a1.log
):
Configuring library for proto-lens-setup-0.4.0.9...
Preprocessing library for proto-lens-setup-0.4.0.9...
Building library for proto-lens-setup-0.4.0.9...
[1 of 2] Compiling Data.ProtoLens.Setup ( src/Data/ProtoLens/Setup.hs, dist/build/Data/ProtoLens/Setup.o, dist/build/Data/ProtoLens/Setup.dyn_o )
src/Data/ProtoLens/Setup.hs:173:33: error: [GHC-83865]
    • Couldn't match type: Distribution.Utils.Path.SymbolicPathX
                             Distribution.Utils.Path.OnlyRelative
                             Distribution.Utils.Path.Pkg
                             Distribution.Utils.Path.File
                     with: [Char]
      Expected: [FilePath]
        Actual: [Distribution.Utils.Path.RelativePath
                   Distribution.Utils.Path.Pkg Distribution.Utils.Path.File]
    • In the second argument of ‘mapM’, namely
        ‘(extraSrcFiles $ localPkgDescr l)’
      In the second argument of ‘(<$>)’, namely
        ‘mapM (match $ localPkgDescr l) (extraSrcFiles $ localPkgDescr l)’
      In a stmt of a 'do' block:
        files <- concat
                   <$>
                     mapM (match $ localPkgDescr l) (extraSrcFiles $ localPkgDescr l)
    |
173 |                                (extraSrcFiles $ localPkgDescr l)
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/ProtoLens/Setup.hs:182:16: error: [GHC-83865]
    • Couldn't match type: Distribution.Utils.Path.SymbolicPathX
                             allowAbs0 dir0 file0
                     with: [Char]
      Expected: IO [FilePath]
        Actual: IO
                  [Distribution.Utils.Path.SymbolicPathX allowAbs0 dir0 file0]
    • In the expression:
        matchDirFileGlob normal (specVersion desc) "." f
      In an equation for ‘match’:
          match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |
182 | match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Data/ProtoLens/Setup.hs:182:59: error: [GHC-83865]
    • Couldn't match type: [Char]
                     with: Maybe
                             (Distribution.Utils.Path.SymbolicPath
                                Distribution.Utils.Path.CWD (Distribution.Utils.Path.Dir dir0))
      Expected: Maybe
                  (Distribution.Utils.Path.SymbolicPath
                     Distribution.Utils.Path.CWD (Distribution.Utils.Path.Dir dir0))
        Actual: String
    • In the third argument of ‘matchDirFileGlob’, namely ‘"."’
      In the expression: matchDirFileGlob normal (specVersion desc) "." f
      In an equation for ‘match’:
          match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |
182 | match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |                                                           ^^^

src/Data/ProtoLens/Setup.hs:182:63: error: [GHC-83865]
    • Couldn't match type: [Char]
                     with: Distribution.Utils.Path.SymbolicPathX allowAbs0 dir0 file0
      Expected: Distribution.Utils.Path.SymbolicPathX
                  allowAbs0 dir0 file0
        Actual: FilePath
    • In the fourth argument of ‘matchDirFileGlob’, namely ‘f’
      In the expression: matchDirFileGlob normal (specVersion desc) "." f
      In an equation for ‘match’:
          match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |
182 | match desc f = matchDirFileGlob normal (specVersion desc) "." f
    |                                                               ^

src/Data/ProtoLens/Setup.hs:257:24: error: [GHC-83865]
    • Couldn't match type: Distribution.Utils.Path.SymbolicPathX
                             Distribution.Utils.Path.AllowAbsolute
                             Distribution.Utils.Path.Pkg
                             (Distribution.Utils.Path.Dir Distribution.Utils.Path.Source)
                     with: [Char]
      Expected: FilePath
        Actual: Distribution.Utils.Path.SymbolicPath
                  Distribution.Utils.Path.Pkg
                  (Distribution.Utils.Path.Dir Distribution.Utils.Path.Source)
    • In the first argument of ‘(</>)’, namely
        ‘autogenComponentModulesDir l compBI’
      In the expression: autogenComponentModulesDir l compBI </> f
      In an equation for ‘dest’:
          dest = autogenComponentModulesDir l compBI </> f
    |
257 |             let dest = autogenComponentModulesDir l compBI </> f
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[2 of 2] Compiling Paths_proto_lens_setup ( dist/build/autogen/Paths_proto_lens_setup.hs, dist/build/Paths_proto_lens_setup.o, dist/build/Paths_proto_lens_setup.dyn_o )
Error: [Cabal-7125]
Failed to build proto-lens-setup-0.4.0.9 (which is required by test:cardano-rpc-test from cardano-rpc-10.2.0.0). See the build log above for details.
```

**Comment by juhp** [comment]
So maybe this should be reopened?

**Comment by carbolymer** [comment]
@blackgnezdo Can we get some help with that?

**Comment by blackgnezdo** [comment]
Sorry guys, life interferes. I'll see if I can do it tonight.

**Comment by blackgnezdo** [comment]
I intend to release what's in #531 once it land.

**Comment by blackgnezdo** [comment]
OK, somebody should the packages I pushed and close the issue.

**Comment by juhp** [comment]
https://www.stackage.org/nightly-2026-04-17/package/proto-lens-setup-0.4.0.10
and https://www.stackage.org/diff/nightly-2026-04-16/nightly-2026-04-17

LGTM

**Comment by carbolymer** [comment]
LGTM! Thanks!
